# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://chamatei.github.io
title: Chama o TÊÍ!
email: chamaotei@gmail.com
author: João Bayer
description: "Pra sua casa ou escritório, chama o TÊÍ - Suporte e Consultoria em Informática."
copyright: 'Copyleft 2019 - TÊÍ . Nenhum direito reservado ;)'
credits: 'Créditos: Desenvolvido com o tema Lading Page do Jekyll, e hospedado com amor no GitHub'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/jgbayer
  - title: contato
    url: https://api.whatsapp.com/send?phone=5521965944972
