# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://chamatei.github.io
title: TÊÍ - Suporte e Consultoria em Informática
email: chamaotei@gmail.com
author: João Bayer
description: "Pra sua casa ou escritório, chama o TÊÍ - Suporte e Consultoria em Informática."
copyright: "Copyleft 2019 - TÊÍ . Livre para copiar ;)"
credits: "Créditos: Desenvolvido com o tema 'Lading Page' do Jekyll, e hospedado com amor no GitHub <3"
logo: '../img/logo.png'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: telefone
    url: https://api.whatsapp.com/send?phone=5521965944972
